app:
  name: 'go-clean-template'
  version: '1.0.0'

http:
  port: '3000'

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

postgres:
  host: 'oupro.cn'
  user: 'postgres'
  password: 'postgres'
  dbname: 'rapid'
  port: 58063
  ssl_mode: 'disable'
  time_zone: 'Asia/Shanghai'

rd_redis:
  addr: 'oupro.cn:6379'
  password: 'liniyuanqu'
